# Generated by Django 4.2.13 on 2026-04-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_accesstoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("HR", "HR"),
                    ("ACCOUNTS", "Accounts"),
                    ("LEGAL", "Legal"),
                    ("FINANCE", "Finance"),
                ],
                default="HR",
                max_length=20,
            ),
        ),
    ]
