# Generated by Django 4.2.30 on 2026-04-22 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_emailotp"),
    ]

    operations = [
        migrations.AddField(
            model_name="accesstoken",
            name="assigned_role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("HR", "HR"),
                    ("ACCOUNTS", "Accounts"),
                    ("LEGAL", "Legal"),
                    ("FINANCE", "Finance"),
                ],
                default="HR",
                max_length=20,
            ),
        ),
    ]
