# Generated by Django 4.2.13 on 2026-04-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_accesstoken_assigned_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailotp",
            name="purpose",
            field=models.CharField(
                choices=[("signup", "Signup"), ("reset_password", "Reset Password")],
                default="signup",
                max_length=20,
            ),
        ),
    ]
