# Generated by Django 4.2.30 on 2026-04-18 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(help_text='The user query text.')),
                ('response', models.TextField(help_text='The AI-generated response.')),
                ('context_chunks', models.TextField(blank=True, default='', help_text='The context chunks used to generate the response.')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'chat_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
