"""
Root URL configuration for the IntraDoc AI project.
"""

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny
from rest_framework.response import Response
from django.http import HttpResponse
from django.views.generic import RedirectView

from ai.views import HealthCheckView


@api_view(['GET'])
@permission_classes([AllowAny])
def api_root(request):
    """
    GET /

    Root endpoint — API documentation and available endpoints.
    """
    return Response({
        'project': 'AI Role-Based Document Retrieval Backend',
        'version': '1.0.0',
        'description': (
            'A RAG-powered backend for role-based document querying. '
            'Upload department-specific PDFs, then query them using natural language. '
            'Responses are generated by Groq LLM using only the relevant document context.'
        ),
        'endpoints': {
            'auth': {
                'register': 'POST /api/auth/register/',
                'login': 'POST /api/auth/login/',
                'profile': 'GET /api/auth/profile/',
                'verify_access_token': 'POST /api/auth/verify-token',
                'create_access_token': 'POST /api/auth/access-tokens/create/',
                'token_refresh': 'POST /api/auth/token/refresh/',
            },
            'documents': {
                'upload': 'POST /api/documents/upload/',
                'list': 'GET /api/documents/',
                'stats': 'GET /api/documents/stats/',
            },
            'chat': {
                'query': 'POST /api/chat/',
                'history': 'GET /api/chat/history/',
            },
            'query_sharing': {
                'hr_query': 'GET /query/hr/',
                'legal_query': 'GET /query/legal/',
                'accounts_query': 'GET /query/accounts/',
                'finance_query': 'GET /query/finance/',
                'admin_query': 'GET /query/admin/',
            },
            'system': {
                'health': 'GET /api/health/',
            },
        },
        'roles': {
            'ADMIN': 'Full access to all departments',
            'HR': 'Access to HR documents only',
            'ACCOUNTS': 'Access to Accounts documents only',
            'LEGAL': 'Access to Legal documents only',
            'FINANCE': 'Access to Finance documents only',
        },
        'test_users': {
            'admin': {'password': 'admin1234', 'role': 'ADMIN'},
            'hr_user': {'password': 'hrpass1234', 'role': 'HR'},
            'accounts_user': {'password': 'accpass1234', 'role': 'ACCOUNTS'},
            'legal_user': {'password': 'legalpass1234', 'role': 'LEGAL'},
        },
        'shareable_links': {
            'description': 'Share pre-configured query forms for each department',
            'example': 'https://yourdomain.com/query/hr/',
            'departments': ['hr', 'legal', 'accounts', 'finance', 'admin'],
        },
    })

def favicon_view(request):
    # Silence /favicon.ico 404 noise in development and admin.
    return HttpResponse(status=204)


urlpatterns = [
    path('api/', api_root, name='api-root'),
    path('favicon.ico', favicon_view, name='favicon'),
    path('', RedirectView.as_view(url='/admin/', permanent=False), name='index'),
    path('admin/', admin.site.urls),
    path('api/auth/', include('users.urls', namespace='users')),
    path('api/documents/', include('documents.urls', namespace='documents')),
    path('api/chat/', include('chat.urls', namespace='chat')),
    path('api/health/', HealthCheckView.as_view(), name='health-check'),
]

# Serve media files in development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
