# Generated by Django 4.2.30 on 2026-04-18 08:30

from django.db import migrations, models
import documents.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=documents.models.document_upload_path)),
                ('department', models.CharField(choices=[('hr', 'HR'), ('accounts', 'Accounts'), ('legal', 'Legal')], db_index=True, max_length=20)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('is_processed', models.BooleanField(default=False, help_text='Whether the document has been processed for embeddings.')),
                ('chunk_count', models.IntegerField(default=0, help_text='Number of text chunks extracted from the document.')),
            ],
            options={
                'db_table': 'documents',
                'ordering': ['-upload_date'],
            },
        ),
    ]
